name: Checks

on: { workflow_call: {} }

jobs:
  format:
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - uses: actions/checkout@v6
      - name: Run format check
        uses: soltiHQ/actions/taskfile@main
        with: { command: ci/format }

  lint:
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - uses: actions/checkout@v6
      - name: Run lint
        uses: soltiHQ/actions/taskfile@main
        with: { command: ci/lint }

  build:
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - uses: actions/checkout@v6
      - name: Run build
        uses: soltiHQ/actions/taskfile@main
        with: { command: ci/build }
