name: Pr

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

permissions: {
  contents: read,
  actions: write,
  pull-requests: read
}

jobs:
  label-check:
    name: Label check
    uses: ./.github/workflows/.label-check.yml

  checks:
    name: Run
    needs: label-check
    uses: ./.github/workflows/.checks.yml

  breaking:
    name: Breaking
    needs: label-check
    uses: ./.github/workflows/.breaking.yml

  pr-check:
    name: Pr Check
    needs: [label-check, checks, breaking]
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - name: All checks passed
        run: echo "All Pr checks completed successfully!"
